git clone https://github.com/liuchengxu/vim-which-key.git 
git clone https://github.com/pgilad/vim-skeletons
git clone https://github.com/SirVer/ultisnips
git clone https://github.com/honza/vim-snippets
git clone https://kien.github.io/ctrlp.vim
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/airblade/vim-gitgutter
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/nathanaelkane/vim-indent-guides
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/kien/ctrlp.vim
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/google/vim-searchindex.git
git clone https://github.com/Valloric/YouCompleteMe
git clone https://github.com/yegappan/grep
git clone https://github.com/wincent/command-t
git clone https://github.com/msanders/snipmate.vim
git clone https://github.com/arcticicestudio/nord-vim
git clone https://github.com/szw/vim-dict
git clone https://github.com/morhetz/gruvbox
git clone https://github.com/ycm-core/YouCompleteMe
git clone https://github.com/neomake/neomake
git clone https://github.com/sheerun/vim-polyglot
git clone https://github.com/wincent/command-t
git clone https://github.com/python-mode/python-mode
git clone https://github.com/easymotion/vim-easymotion
git clone https://github.com/neoclide/coc-python
git clone https://github.com/google/yapf
git clone https://github.com/Vimjas/vim-python-pep8-indent
git clone https://github.com/frazrepo/vim-rainbow
